# Generated by Django 4.2.3 on 2023-07-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brgy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brgy_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purok_name', models.CharField(max_length=150)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.brgy')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateTimeField()),
                ('birth_place', models.CharField(max_length=100)),
                ('civil_status', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('voter', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.purok')),
            ],
        ),
        migrations.CreateModel(
            name='Solo_parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=100)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Pwd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Ofw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=150)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.brgy')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField()),
                ('cause_of_death', models.CharField(max_length=100)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
    ]
