# Generated by Django 4.2.3 on 2023-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
