# Generated by Django 4.2.3 on 2023-08-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0002_alter_resident_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solo_parent',
            name='resident',
        ),
        migrations.AddField(
            model_name='resident',
            name='pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='solo_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pwd',
        ),
        migrations.DeleteModel(
            name='Solo_parent',
        ),
    ]
