# Generated by Django 4.2.3 on 2023-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0004_remove_household_brgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='house_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='relation_to_head',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
