# Generated by Django 4.2.3 on 2023-08-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0005_household_head_household_house_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='house_no',
            field=models.IntegerField(max_length=150),
        ),
    ]
