# Generated by Django 4.2.3 on 2023-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0007_rename_death_date_deceased_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='house_no',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Blotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('complainants', models.ManyToManyField(related_name='complaints', to='BrgyApp.resident')),
                ('respondents', models.ManyToManyField(related_name='responses', to='BrgyApp.resident')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
