# Generated by Django 4.2.3 on 2023-08-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0008_alter_household_house_no_blotter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blotter',
            options={},
        ),
    ]
