# Generated by Django 4.2.3 on 2023-08-04 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0009_alter_blotter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blotter',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='blotter',
            name='complainants',
        ),
        migrations.RemoveField(
            model_name='blotter',
            name='respondents',
        ),
        migrations.AddField(
            model_name='blotter',
            name='complainants',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='BrgyApp.resident'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blotter',
            name='respondents',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='BrgyApp.resident'),
            preserve_default=False,
        ),
    ]
