# Generated by Django 4.2.3 on 2023-08-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0010_alter_blotter_options_remove_blotter_complainants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('proprietor', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('purok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.purok')),
            ],
        ),
    ]
