# Generated by Django 4.2.3 on 2023-08-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0012_businessclearance_brgyclearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertSoloParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('clearance_type', models.CharField(max_length=100)),
                ('or_no', models.CharField(max_length=50)),
                ('or_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('or_date', models.DateField()),
                ('ctc', models.CharField(max_length=50)),
                ('ctc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctc_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='CertResidency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('clearance_type', models.CharField(max_length=100)),
                ('or_no', models.CharField(max_length=50)),
                ('or_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('or_date', models.DateField()),
                ('ctc', models.CharField(max_length=50)),
                ('ctc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctc_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='CertNonOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceased_date', models.DateField()),
                ('purpose', models.CharField(max_length=100)),
                ('clearance_type', models.CharField(max_length=100)),
                ('or_no', models.CharField(max_length=50)),
                ('or_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('or_date', models.DateField()),
                ('ctc', models.CharField(max_length=50)),
                ('ctc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctc_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.business')),
            ],
        ),
        migrations.CreateModel(
            name='CertIndegency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('clearance_type', models.CharField(max_length=100)),
                ('or_no', models.CharField(max_length=50)),
                ('or_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('or_date', models.DateField()),
                ('ctc', models.CharField(max_length=50)),
                ('ctc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctc_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
        migrations.CreateModel(
            name='CertGoodMoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('clearance_type', models.CharField(max_length=100)),
                ('or_no', models.CharField(max_length=50)),
                ('or_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('or_date', models.DateField()),
                ('ctc', models.CharField(max_length=50)),
                ('ctc_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctc_date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.resident')),
            ],
        ),
    ]
