# Generated by Django 4.2.3 on 2023-08-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0013_certsoloparent_certresidency_certnonoperation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertIndegency',
            new_name='CertIndigency',
        ),
    ]
