# Generated by Django 4.2.3 on 2023-08-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0015_certtribal'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='citizenship',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
