# Generated by Django 4.2.3 on 2023-08-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0017_remove_businessclearance_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='head',
        ),
        migrations.RemoveField(
            model_name='household',
            name='relation_to_head',
        ),
        migrations.RemoveField(
            model_name='household',
            name='resident',
        ),
        migrations.AddField(
            model_name='household',
            name='purok',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.purok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='household_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
