# Generated by Django 4.2.3 on 2023-08-20 18:06

import BrgyApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0018_remove_household_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='household_no',
        ),
        migrations.AddField(
            model_name='resident',
            name='house_no',
            field=models.CharField(default=1, verbose_name=BrgyApp.models.Household),
            preserve_default=False,
        ),
    ]
