# Generated by Django 4.2.3 on 2023-08-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0024_alter_resident_house_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='house_no',
        ),
    ]
