# Generated by Django 4.2.3 on 2023-08-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0025_remove_resident_house_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='house_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
