# Generated by Django 4.2.3 on 2023-08-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0026_resident_house_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='brgy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='brgy',
            name='municipality',
            field=models.CharField(default='Tuguegarao', max_length=150),
            preserve_default=False,
        ),
    ]
