# Generated by Django 4.2.3 on 2023-10-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0027_brgy_image_brgy_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brgy_Officials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brgy_Captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brgy_Captain', to='BrgyApp.resident')),
                ('kagawad1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kagawad1', to='BrgyApp.resident')),
                ('kagawad2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kagawad2', to='BrgyApp.resident')),
                ('kagawad3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kagawad3', to='BrgyApp.resident')),
                ('kagawad4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kagawad4', to='BrgyApp.resident')),
                ('kagawad5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kagawad5', to='BrgyApp.resident')),
                ('kagawad6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kagawad6', to='BrgyApp.resident')),
                ('kagawad7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kagawad7', to='BrgyApp.resident')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='BrgyApp.resident')),
                ('sk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sk', to='BrgyApp.resident')),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer', to='BrgyApp.resident')),
            ],
        ),
    ]
