# Generated by Django 4.2.3 on 2023-10-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0028_brgy_officials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='house_type',
            new_name='address',
        ),
    ]
