# Generated by Django 4.2.3 on 2023-10-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0030_rename_address_household_house_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='house_type',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='purok',
        ),
        migrations.AlterField(
            model_name='resident',
            name='house_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BrgyApp.household'),
            preserve_default=False,
        ),
    ]
