# Generated by Django 4.2.3 on 2023-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrgyApp', '0033_jobseekers'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='indigent',
            field=models.BooleanField(default=False),
        ),
    ]
